/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRobloxKeyRouteImport } from './routes/api/roblox/key'
import { Route as ApiRobloxForceCheckRouteImport } from './routes/api/roblox/force-check'
import { Route as ApiRobloxExperiencesRouteImport } from './routes/api/roblox/experiences'
import { Route as ApiPublicRunChecksRouteImport } from './routes/api/public/run-checks'
import { Route as ApiPublicHourlySummaryRouteImport } from './routes/api/public/hourly-summary'
import { Route as ApiAuthPinRouteImport } from './routes/api/auth/pin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRobloxKeyRoute = ApiRobloxKeyRouteImport.update({
  id: '/api/roblox/key',
  path: '/api/roblox/key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRobloxForceCheckRoute = ApiRobloxForceCheckRouteImport.update({
  id: '/api/roblox/force-check',
  path: '/api/roblox/force-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRobloxExperiencesRoute = ApiRobloxExperiencesRouteImport.update({
  id: '/api/roblox/experiences',
  path: '/api/roblox/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunChecksRoute = ApiPublicRunChecksRouteImport.update({
  id: '/api/public/run-checks',
  path: '/api/public/run-checks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHourlySummaryRoute = ApiPublicHourlySummaryRouteImport.update({
  id: '/api/public/hourly-summary',
  path: '/api/public/hourly-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPinRoute = ApiAuthPinRouteImport.update({
  id: '/api/auth/pin',
  path: '/api/auth/pin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/pin': typeof ApiAuthPinRoute
  '/api/public/hourly-summary': typeof ApiPublicHourlySummaryRoute
  '/api/public/run-checks': typeof ApiPublicRunChecksRoute
  '/api/roblox/experiences': typeof ApiRobloxExperiencesRoute
  '/api/roblox/force-check': typeof ApiRobloxForceCheckRoute
  '/api/roblox/key': typeof ApiRobloxKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/pin': typeof ApiAuthPinRoute
  '/api/public/hourly-summary': typeof ApiPublicHourlySummaryRoute
  '/api/public/run-checks': typeof ApiPublicRunChecksRoute
  '/api/roblox/experiences': typeof ApiRobloxExperiencesRoute
  '/api/roblox/force-check': typeof ApiRobloxForceCheckRoute
  '/api/roblox/key': typeof ApiRobloxKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/auth/pin': typeof ApiAuthPinRoute
  '/api/public/hourly-summary': typeof ApiPublicHourlySummaryRoute
  '/api/public/run-checks': typeof ApiPublicRunChecksRoute
  '/api/roblox/experiences': typeof ApiRobloxExperiencesRoute
  '/api/roblox/force-check': typeof ApiRobloxForceCheckRoute
  '/api/roblox/key': typeof ApiRobloxKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/pin'
    | '/api/public/hourly-summary'
    | '/api/public/run-checks'
    | '/api/roblox/experiences'
    | '/api/roblox/force-check'
    | '/api/roblox/key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/pin'
    | '/api/public/hourly-summary'
    | '/api/public/run-checks'
    | '/api/roblox/experiences'
    | '/api/roblox/force-check'
    | '/api/roblox/key'
  id:
    | '__root__'
    | '/'
    | '/api/auth/pin'
    | '/api/public/hourly-summary'
    | '/api/public/run-checks'
    | '/api/roblox/experiences'
    | '/api/roblox/force-check'
    | '/api/roblox/key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuthPinRoute: typeof ApiAuthPinRoute
  ApiPublicHourlySummaryRoute: typeof ApiPublicHourlySummaryRoute
  ApiPublicRunChecksRoute: typeof ApiPublicRunChecksRoute
  ApiRobloxExperiencesRoute: typeof ApiRobloxExperiencesRoute
  ApiRobloxForceCheckRoute: typeof ApiRobloxForceCheckRoute
  ApiRobloxKeyRoute: typeof ApiRobloxKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roblox/key': {
      id: '/api/roblox/key'
      path: '/api/roblox/key'
      fullPath: '/api/roblox/key'
      preLoaderRoute: typeof ApiRobloxKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roblox/force-check': {
      id: '/api/roblox/force-check'
      path: '/api/roblox/force-check'
      fullPath: '/api/roblox/force-check'
      preLoaderRoute: typeof ApiRobloxForceCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roblox/experiences': {
      id: '/api/roblox/experiences'
      path: '/api/roblox/experiences'
      fullPath: '/api/roblox/experiences'
      preLoaderRoute: typeof ApiRobloxExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/run-checks': {
      id: '/api/public/run-checks'
      path: '/api/public/run-checks'
      fullPath: '/api/public/run-checks'
      preLoaderRoute: typeof ApiPublicRunChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hourly-summary': {
      id: '/api/public/hourly-summary'
      path: '/api/public/hourly-summary'
      fullPath: '/api/public/hourly-summary'
      preLoaderRoute: typeof ApiPublicHourlySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/pin': {
      id: '/api/auth/pin'
      path: '/api/auth/pin'
      fullPath: '/api/auth/pin'
      preLoaderRoute: typeof ApiAuthPinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthPinRoute: ApiAuthPinRoute,
  ApiPublicHourlySummaryRoute: ApiPublicHourlySummaryRoute,
  ApiPublicRunChecksRoute: ApiPublicRunChecksRoute,
  ApiRobloxExperiencesRoute: ApiRobloxExperiencesRoute,
  ApiRobloxForceCheckRoute: ApiRobloxForceCheckRoute,
  ApiRobloxKeyRoute: ApiRobloxKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
