/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicRunChecksRouteImport } from './routes/api/public/run-checks'
import { Route as ApiAuthPinRouteImport } from './routes/api/auth/pin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPinRoute = ApiAuthPinRouteImport.update({
  id: '/api/auth/pin',
  path: '/api/auth/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunChecksRoute = ApiPublicRunChecksRouteImport.update({
  id: '/api/public/run-checks',
  path: '/api/public/run-checks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/pin': typeof ApiAuthPinRoute
  '/api/public/run-checks': typeof ApiPublicRunChecksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/pin': typeof ApiAuthPinRoute
  '/api/public/run-checks': typeof ApiPublicRunChecksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/auth/pin': typeof ApiAuthPinRoute
  '/api/public/run-checks': typeof ApiPublicRunChecksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/auth/pin' | '/api/public/run-checks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/auth/pin' | '/api/public/run-checks'
  id: '__root__' | '/' | '/api/auth/pin' | '/api/public/run-checks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuthPinRoute: typeof ApiAuthPinRoute
  ApiPublicRunChecksRoute: typeof ApiPublicRunChecksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/pin': {
      id: '/api/auth/pin'
      path: '/api/auth/pin'
      fullPath: '/api/auth/pin'
      preLoaderRoute: typeof ApiAuthPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/run-checks': {
      id: '/api/public/run-checks'
      path: '/api/public/run-checks'
      fullPath: '/api/public/run-checks'
      preLoaderRoute: typeof ApiPublicRunChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthPinRoute: ApiAuthPinRoute,
  ApiPublicRunChecksRoute: ApiPublicRunChecksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
