// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { supabaseAdmin as _shim } from "@/lib/db.server";

// Re-export the shimbed supabaseAdmin implemented on top of SQLite.
export const supabaseAdmin = _shim;
